server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://127.0.0.1:8761/eureka/