server:
  port: 8761
eureka:
  client:
    #是否将自己注册到Eureka-Server中，默认的为true
    #register-with-eureka: false
    #是否从Eureka-Server中获取服务注册信息，默认为true
    #fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://127.0.0.1:8762/eureka/
spring:
  application:
    name: eureka-server